[package]
name = "planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.8"
rppal = "0.17.1"
prost = "0.12"
uom = "0.35.0"
rand = "0.8.5"

[build-dependencies]
prost-build = "0.12"